export const client = {
  name: "Three Acorns Landscaping",
  tagline: "Professional Landscaper in Newcastle — Quality You Can Trust",
  description: "Professional landscaper services in Newcastle and surrounding areas. Trusted local experts with 13 Google reviews.",
  category: "Landscaper",
  yearEstablished: "2015",
  phone: "",
  email: "",
  website: "",
  address: "",
  city: "Newcastle",
  county: "",
  postcode: "",
  basedIn: "Newcastle",
  founderName: "Lucy",
  founderSurname: "",
  founderRole: "Director",
  facebook: "",
  instagram: "",
  linkedin: "",
  twitter: "",
  googleRating: "4.7",
  reviewCount: "13",
  services: [
    { title: "Garden Design", description: "Bespoke garden designs tailored to your lifestyle and space.", icon: "tree" },
    { title: "Landscaping", description: "Complete hard and soft landscaping to transform your outdoor area.", icon: "shovel" },
    { title: "Paving & Patios", description: "Beautiful paving solutions using premium natural stone and porcelain.", icon: "wall" },
    { title: "Planting Schemes", description: "Year-round colour and interest with expertly curated planting plans.", icon: "flower" },
  ],
  cinematic: {
    frameCount: 181, frameDir: "/frames/", framePrefix: "frame_", frameExtension: ".jpg",
    framePadding: 4, scrollLength: "500vh", mobileFrameCount: 181, mobileFrameDir: "/frames-mobile/",
    scrubSpeed: 0.5, heroStillImage: "/images/hero-still.jpg", heroStillImageMobile: "/images/hero-still-mobile.jpg",
  },
  beforeAfter: { beforeImage: "/images/before.jpg", afterImage: "/images/after.jpg", beforeLabel: "Current Garden", afterLabel: "Our Vision" },
  transformations: [
    { before: "/images/before.jpg", after: "/images/after.jpg", label: "Complete Garden Renovation" },
    { before: "/images/patio-before.jpg", after: "/images/patio-after.jpg", label: "Patio & Fencing" },
    { before: "/images/front-before.jpg", after: "/images/front-after.jpg", label: "Front Garden" },
    { before: "/images/lawn-before.jpg", after: "/images/lawn-after.jpg", label: "Lawn Restoration" },
    { before: "/images/fence-before.jpg", after: "/images/fence-after.jpg", label: "New Fencing" },
    { before: "/images/deck-before.jpg", after: "/images/deck-after.jpg", label: "Decking & Furniture" },
    { before: "/images/path-before.jpg", after: "/images/path-after.jpg", label: "Garden Path" },
    { before: "/images/border-before.jpg", after: "/images/border-after.jpg", label: "Planting Borders" },
    { before: "/images/drive-before.jpg", after: "/images/drive-after.jpg", label: "Driveway" },
  ] as { before: string; after: string; label: string }[],
  reviews: [
    { name: "M Kesic", rating: 5, text: "We have used Three Acorns services since 2018 and both Will and Wayne have always been professional, reliable and friendly. Will always offers great advice, is honest and we feel that we can trust his judgement and let him do the job without any concerns. The work is carried out to a high standard. Prices are reasonable. They always tidy up afterwards, we never need to do anything, Wayne leaves the working area spotless. Conscientious workers, would totally recommend.", date: "10 months ago" },
    { name: "Corrina Cook", rating: 5, text: "Amazing service from start to finish! Experts in their field and provide their best advice. Hard working, professional and take pride in what they do resulting in my garden being landscaped and looking incredible. Really friendly and trustworthy, easy to get on with I'm so glad I found these! Thank you so much!", date: "4 years ago" },
    { name: "Wayne Burton", rating: 5, text: "Will & his team had the task of designing and fully landscaping our back garden. They executed every element with sheer professionalism and in such fantastic detail. The garden is absolutely fabulous and it couldn't be any better. I cannot praise Will & his team enough. Highly, highly recommended.", date: "4 years ago" },
    { name: "John C", rating: 5, text: "A Top Top team. William and his colleagues cleared an overgrown jungle, tree and bush stumps and including the rubbish hidden for what looks like years in the bushes. They have left the whole area immeasurably improved ready for seeding a new lawn. Very polite, considerate of others including the neighbours and hard working.", date: "5 years ago", badge: "Local Guide" },
    { name: "Thomas Micheal", rating: 1, text: "Not bad", date: "Edited 5 years ago" },
    { name: "Alex Allan", rating: 5, text: "Had three acorns back to do more work for us as there work is extremely  good i would recommend  there always on time  dont leave site till it's all cleaned up  will be having them back again and next door is going to use them", date: "5 years ago" },
  ] as { name: string; rating: number; text: string; date: string; badge?: string }[],
  seo: {
    title: "Three Acorns Landscaping | Professional Landscaper in Newcastle",
    description: "Professional landscaper in Newcastle. 4.7 stars on Google with 13 reviews. Quality workmanship guaranteed.",
  },
};
